#ifndef MINIZ_EXPORT_H
#define MINIZ_EXPORT_H

/* Hand-written stand-in for upstream miniz's miniz_export.h, which is
 * generated by their CMake build (GenerateExportHeader) and does not exist
 * as a static file in the miniz source tree. This project links tinfl
 * statically into one binary -- no shared-library export/import boundary
 * exists, so MINIZ_EXPORT has nothing to do. */
#define MINIZ_EXPORT

#endif /* MINIZ_EXPORT_H */
